 # theme = "mytheme"
 theme = "newtheme"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ["goto_last_accessed_file"]
"A-q" = "goto_line_start"
"A-e" = "goto_line_end"
"C-w" = ":bc"
"A-left" = ":buffer-previous"
"A-right" = ":buffer-next"
"A-h" = ":buffer-previous"
"A-l" = ":buffer-next"
"C-s" = ":w"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]


[keys.insert]
"C-space" = "completion"
 C-s = ["normal_mode", ":w"]

[keys.normal.space]
tab = ":config-reload"
q = [":o ~/.config/helix/themes/newtheme.toml", ":o ~/work/chat_app/src/components/modals/RatingModal.vue", ":o ~/work/chat_app/src/types/interfaces/strapi.interfaces.ts",":o ~/github/rustproject/src/main.rs"]
i = ":tree-sitter-highlight-name"
u = ":tree-sitter-scopes"
o = ":tree-sitter-subtree"
# adding custom Description is not currently supported - https://github.com/helix-editor/helix/issues/1752
# 1g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor]
bufferline = "multiple"
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
