[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
# language-servers = ["typescript-language-server", "vuels" ]
language-servers = ["typescript-language-server", "tailwindcss-ls"]

# [language-server.typescript-language-server]
# command = "typescript-language-server"
# args = ["--stdio"]

# [language-server.vuels]
# command = "vue-language-server"
# args = ["--stdio"]

[language-server.typescript-language-server.config]
plugins = [{ name = "@vue/typescript-plugin", location = "/usr/lib/node_modules/@vue/language-server", languages = ["vue"] }]


# [[language-server.typescript-language-server.config.plugins]]
# name = "@vue/typescript-plugin"
# location = "/usr/lib/node_modules/@vue/language-server"
# languages = ["vue"]

[language-server.vuels.config]
typescript = { tsdk = "/usr/lib/node_modules/typescript/lib/" }
vue = { hybridMode = true }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]
