[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
# language-servers = ["typescript-language-server", "vuels" ]
language-servers = ["typescript-language-server"]

# [language-server.typescript-language-server]
# command = "typescript-language-server"
# args = ["--stdio"]

# [language-server.vuels]
# command = "vue-language-server"
# args = ["--stdio"]

[language-server.typescript-language-server.config]
plugins = [{ name = "@vue/typescript-plugin", location = "/usr/lib/node_modules/@vue/language-server", languages = ["vue"] }]


# [[language-server.typescript-language-server.config.plugins]]
# name = "@vue/typescript-plugin"
# location = "/usr/lib/node_modules/@vue/language-server"
# languages = ["vue"]

[language-server.vuels.config]
typescript = { tsdk = "/usr/lib/node_modules/typescript/lib/" }
vue = { hybridMode = true }

