[[language]]
name = "vue"
scope = "source.vue"
file-types = ["vue"]
grammar = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server", "vuels", "tailwindcss-ls"]

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/lulz/.nvm/versions/node/v24.17.0/lib/node_modules/@vue/language-server"
languages = ["vue"]

[language-server.vuels.config]
typescript = { tsdk = "/home/lulz/.nvm/versions/node/v24.17.0/lib/node_modules/typescript/lib/" }
vue = { hybridMode = true }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
injection-regex = "css"

[[language]]
name = "javascript"
injection-regex = "javascript"

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]



[haskell]
language-server = "/home/lulz/.ghcup/bin/haskell-language-server-wrapper"
